blogcode/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [

path('', views.about, name='about'),

]

blogcode/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

path('', views.signup_view, name='signup'),

]

blogcode/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [

    path('', views.startpage, name='startpage'),
    path('<slug>/', views.article_detail, name='article_detail'),




]

blogcode/horror_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [


    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('about/', include('about.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogcode/about/models.py
from django.db import models

class About(models.Model):
    title = models.CharField(max_length=125)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:200] + '...'

blogcode/accounts/models.py
from django.db import models

# Create your models here.

blogcode/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=125)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.CharField(max_length=125, default='Patrick Gabbard')


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:200] + '...'




    #add in thumbnail later
    #add in author later

blogcode/about/views.py
from django.shortcuts import render
from .models import About
from django.http import HttpResponse

def about(request):


    return render(request, 'about/about_page.html')

# Create your views here.

blogcode/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            #put login here
            return redirect('articles:startpage')
    else:
        form = UserCreationForm()
        return render(request, 'accounts/signup.html', { 'form': form })

blogcode/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse


def startpage(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/homepage.html', {'articles': articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

blogcode/about/templates/about/about_page.html
{% extends 'base_layouts.html' %}

{% block content %}
  <h1>About</h1>
  <h2>{{ about.title }}</h2>
  <p>{{ about.body }}</p>
  <p>{{ about.date }}</p>
{% endblock %}

blogcode/accounts/templates/accounts/signup.html
{% extends 'base_layouts.html' %}

{% block content %}
  <h1>Signup</h1>
  <form class="site-form" action="/accounts/signup.html/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

blogcode/articles/templates/articles/article_detail.html
{% extends 'base_layouts.html' %}

{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumb.url }}"/>
    <h2>{{ article.title }}</h2>
    <h3>{{ article.author }}</h3>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
  </div>
</div>

{% endblock %}

blogcode/articles/templates/articles/homepage.html
{% extends 'base_layouts.html' %}
{% block content %}
    <h1>This Month's Reviews</h1>
    <div class="articles">
      {% for article in articles %}
        <div class="article">
          <h2><a href={% url 'articles:article_detail' slug=article.slug %}>{{ article.title }}</a></h2>
          <p>{{ article.snippet }}</p>
          <p>{{ article.date }}</p>
        </div>
      {% endfor %}
    </div>
{% endblock %}

blogcode/templates/base_layouts.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome to Oblivion: The Latest in Horror Cinema</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <h1><a href={% url 'articles:startpage' %}><img src="{% static 'Pentacle.png' %}"</a></h1>
      {% block content %}
      {% endblock %}
    </div>
</body>
</html>

blogcode/templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
  </head>
    <h1>BlogBlogBlogBlog</h1>
  <body>

  </body>
</html>